apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storageos-tools
  labels:
    app: storageos-tools
spec:
  selector:
    matchLabels:
      app: storageos-tools
  template:
    metadata:
      labels:
        app: storageos-tools
    spec:
      containers:
      - name: storageos-tools
        image: shakapark/storageos-tools:v0.1.0
        ports:
          - containerPort: 8080
        env:
          - name: ETCD_URLS
            value: "http://51.91.134.159:2379"
          - name: NODE_HOSTNAME
            valueFrom: 
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_PATHFILE
            value: /mnt/storageos/id
        volumeMounts:
          - mountPath: /mnt/storageos/id
            name: storageos

        livenessProbe:
          httpGet:
            port: 8080
            path: /check/node/id
          initialDelaySeconds: 0

        readinessProbe:
          httpGet:
            port: 8080
            path: /check/node/id
          initialDelaySeconds: 0

      volumes:
        - name: storageos
          hostPath:
            path: /var/lib/storageos/state/id
            type: File
